name: Build and Deploy

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Node.js modules
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-
      - run: yarn install --prefer-offline
      - run: yarn build --modern && sed -i 's/fonts.gstatic.com/fonts.kavin.rocks/g' dist/css/*.css
      - uses: aquiladev/ipfs-action@v0.1.5
        id: ipfs-add
        with:
          path: ./dist
          service: infura
      - name: Update DNSLink
        run: npx dnslink-cloudflare -d kavin.rocks -l /ipfs/${{ steps.ipfs-add.outputs.hash }} -r _dnslink.piped-ipfs
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
