name: reviewdog
on: [pull_request]
jobs:
    eslint:
        name: runner / eslint
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  cache: "pnpm"
            - run: pnpm install
            - uses: reviewdog/action-eslint@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  reporter: github-pr-review
                  eslint_flags: "--ignore-path .gitignore --ext .js,.vue ."
